[[main]]
  name = "About"
  pageRef = "about"
  weight = 1

[[main]]
  name = "Blog"
  weight = 2
  pageRef = "blog"

[[main]]
  name = "Contact"
  weight = 4
  pageRef = "contact"

[[main]]
  name = ""
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/bryskiewiczr"
  target = "_blank"
  weight = 6

[[main]]
  name = ""
  identifier = "github"
  pre = "github"
  url = "https://www.github.com/bryskiewiczr"
  target = "_blank"
  weight = 7